simulation:
  dt: 0.01           # Time step (seconds)
  gamma: 1.0         # Damping coefficient (s^-1)
  temp: 0.02         # Temperature (meV)
  mass: 1.0          # Mass of particle (amu)
  nsteps: 1000       # Number of simulation steps
  num_particles: 3   # Number of particles

pes:
  C0_min: 1.63093e6  # Minimum C0 value (meV)
  C0_max: 2.75075e6  # Maximum C0 value (meV)
  C1_min: 3.347616   # Minimum C1 value (Å^-1)
  C1_max: 3.349208   # Maximum C1 value (Å^-1)
  C2_min: 8184.7     # Minimum C2 value (meV Å^4)
  C2_max: 8258.11    # Maximum C2 value (meV Å^4)
  lattice_constant: 2.462  # Lattice constant (Å)
